---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/register":
    post:
      summary: Register new user
      tags:
      - Auth
      parameters: []
      responses:
        '201':
          description: user registered
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/api/v1/login":
    post:
      summary: Login user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: user logged in
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/links":
    post:
      summary: Create Short URL
      tags:
      - Links
      security:
      - Bearer: []
      parameters: []
      responses:
        '201':
          description: URL created
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link:
                  type: object
                  properties:
                    original_url:
                      type: string
                  required:
                  - original_url
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWT Authorization header using the Bearer scheme. Example: ''Bearer
        <token>'''
servers:
- schemes:
  - http
  url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
